# Cloud Build configuration for BGG processor
steps:
  # Build the processor image with environment tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT']

  # Deploy Fetch IDs Cloud Run Job - Create if not exists, otherwise update
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gcloud run jobs describe bgg-fetch-ids-$_ENVIRONMENT --region=us-central1 2>/dev/null; then
          echo "Updating existing job: bgg-fetch-ids-$_ENVIRONMENT"
          gcloud run jobs update bgg-fetch-ids-$_ENVIRONMENT \
            --image=gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT \
            --args=src.pipeline.fetch_ids \
            --tasks=1 \
            --max-retries=2 \
            --task-timeout=30m \
            --memory=1Gi \
            --cpu=1 \
            --region=us-central1 \
            --service-account=bgg-data-warehouse@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=ENVIRONMENT=$_ENVIRONMENT
        else
          echo "Creating new job: bgg-fetch-ids-$_ENVIRONMENT"
          gcloud run jobs create bgg-fetch-ids-$_ENVIRONMENT \
            --image=gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT \
            --args=src.pipeline.fetch_ids \
            --tasks=1 \
            --max-retries=2 \
            --task-timeout=30m \
            --memory=1Gi \
            --cpu=1 \
            --region=us-central1 \
            --service-account=bgg-data-warehouse@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=ENVIRONMENT=$_ENVIRONMENT
        fi

  # Deploy Fetch Responses Cloud Run Job - Create if not exists, otherwise update
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gcloud run jobs describe bgg-fetch-responses-$_ENVIRONMENT --region=us-central1 2>/dev/null; then
          echo "Updating existing job: bgg-fetch-responses-$_ENVIRONMENT"
          gcloud run jobs update bgg-fetch-responses-$_ENVIRONMENT \
            --image=gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT \
            --args=src.pipeline.fetch_responses \
            --tasks=1 \
            --max-retries=3 \
            --task-timeout=2h \
            --memory=2Gi \
            --cpu=1 \
            --region=us-central1 \
            --service-account=bgg-data-warehouse@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=ENVIRONMENT=$_ENVIRONMENT,BGG_API_TOKEN=$_BGG_API_TOKEN
        else
          echo "Creating new job: bgg-fetch-responses-$_ENVIRONMENT"
          gcloud run jobs create bgg-fetch-responses-$_ENVIRONMENT \
            --image=gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT \
            --args=src.pipeline.fetch_responses \
            --tasks=1 \
            --max-retries=3 \
            --task-timeout=2h \
            --memory=2Gi \
            --cpu=1 \
            --region=us-central1 \
            --service-account=bgg-data-warehouse@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=ENVIRONMENT=$_ENVIRONMENT,BGG_API_TOKEN=$_BGG_API_TOKEN
        fi

  # Deploy Process Responses Cloud Run Job - Create if not exists, otherwise update
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gcloud run jobs describe bgg-process-responses-$_ENVIRONMENT --region=us-central1 2>/dev/null; then
          echo "Updating existing job: bgg-process-responses-$_ENVIRONMENT"
          gcloud run jobs update bgg-process-responses-$_ENVIRONMENT \
            --image=gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT \
            --args=src.pipeline.process_responses \
            --tasks=1 \
            --max-retries=3 \
            --task-timeout=2h \
            --memory=4Gi \
            --cpu=2 \
            --region=us-central1 \
            --service-account=bgg-data-warehouse@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=ENVIRONMENT=$_ENVIRONMENT
        else
          echo "Creating new job: bgg-process-responses-$_ENVIRONMENT"
          gcloud run jobs create bgg-process-responses-$_ENVIRONMENT \
            --image=gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT \
            --args=src.pipeline.process_responses \
            --tasks=1 \
            --max-retries=3 \
            --task-timeout=2h \
            --memory=4Gi \
            --cpu=2 \
            --region=us-central1 \
            --service-account=bgg-data-warehouse@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars=ENVIRONMENT=$_ENVIRONMENT
        fi

# Images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/bgg-processor:$_ENVIRONMENT'

# Timeout for the entire build
timeout: '1800s'  # 30 minutes
