# Cloud Build configuration for BGG processor
steps:
  # Build the processor image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bgg-processor', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bgg-processor']

  # Deploy Fetch Responses Cloud Run Job
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'bgg-fetch-responses'
      - '--image=gcr.io/$PROJECT_ID/bgg-processor'
      - '--tasks=3'  # Fewer tasks for fetching
      - '--max-retries=3'
      - '--task-timeout=1h'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--region=us-central1'
      - '--service-account=bgg-data-warehouse@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=ENVIRONMENT=dev,PIPELINE_STAGE=fetch_responses'

  # Deploy Process Responses Cloud Run Job
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'bgg-process-responses'
      - '--image=gcr.io/$PROJECT_ID/bgg-processor'
      - '--tasks=5'  # More tasks for processing
      - '--max-retries=3'
      - '--task-timeout=1h'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--region=us-central1'
      - '--service-account=bgg-data-warehouse@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=ENVIRONMENT=dev,PIPELINE_STAGE=process_responses'

# Images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/bgg-processor'

# Timeout for the entire build
timeout: '1800s'  # 30 minutes
